apiVersion: batch/v1
kind: CronJob
metadata:
  name: vinted-notifier-cronjob
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: vinted-notifier
              image: registry.gitlab.com/airklizz/vinted-notifier:v0.1
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: slack-bot-token
          restartPolicy: Never
