apiVersion: v1
kind: Service
metadata:
  name: selenium
  namespace: selenium
spec:
  ports:
    - name: http
      port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    app: selenium
  type: ClusterIP
